# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(924, 819)
        self.movieLabel = QtWidgets.QLabel(Dialog)
        self.movieLabel.setGeometry(QtCore.QRect(20, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.movieLabel.setFont(font)
        self.movieLabel.setObjectName("movieLabel")
        self.nextBttn = QtWidgets.QPushButton(Dialog)
        self.nextBttn.setGeometry(QtCore.QRect(70, 630, 121, 51))
        self.nextBttn.setObjectName("nextBttn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 50, 171, 211))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(480, 50, 171, 211))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(730, 50, 171, 211))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(480, 290, 171, 211))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(730, 290, 171, 211))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 290, 171, 211))
        self.label_2.setObjectName("label_2")
        self.label_selected = QtWidgets.QLabel(Dialog)
        self.label_selected.setGeometry(QtCore.QRect(20, 60, 171, 211))
        self.label_selected.setObjectName("label_selected")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(470, 540, 171, 211))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 540, 171, 211))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(710, 540, 171, 211))
        self.label_9.setObjectName("label_9")
        self.overview = QtWidgets.QTextEdit(Dialog)
        self.overview.setGeometry(QtCore.QRect(10, 360, 181, 201))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.overview.setFont(font)
        self.overview.setReadOnly(True)
        self.overview.setObjectName("overview")
        self.seenLabel_2 = QtWidgets.QLabel(Dialog)
        self.seenLabel_2.setGeometry(QtCore.QRect(20, 340, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.seenLabel_2.setFont(font)
        self.seenLabel_2.setObjectName("seenLabel_2")
        self.seenLabel_3 = QtWidgets.QLabel(Dialog)
        self.seenLabel_3.setGeometry(QtCore.QRect(230, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_3.setFont(font)
        self.seenLabel_3.setObjectName("seenLabel_3")
        self.seenLabel_4 = QtWidgets.QLabel(Dialog)
        self.seenLabel_4.setGeometry(QtCore.QRect(480, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_4.setFont(font)
        self.seenLabel_4.setObjectName("seenLabel_4")
        self.seenLabel_5 = QtWidgets.QLabel(Dialog)
        self.seenLabel_5.setGeometry(QtCore.QRect(760, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_5.setFont(font)
        self.seenLabel_5.setObjectName("seenLabel_5")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(200, -170, 20, 931))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(440, -170, 20, 931))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(680, -170, 20, 931))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.use1 = QtWidgets.QTextEdit(Dialog)
        self.use1.setGeometry(QtCore.QRect(230, 770, 201, 41))
        self.use1.setReadOnly(True)
        self.use1.setObjectName("use1")
        self.use2 = QtWidgets.QTextEdit(Dialog)
        self.use2.setGeometry(QtCore.QRect(470, 770, 201, 41))
        self.use2.setReadOnly(True)
        self.use2.setObjectName("use2")
        self.use3 = QtWidgets.QTextEdit(Dialog)
        self.use3.setGeometry(QtCore.QRect(710, 770, 201, 41))
        self.use3.setReadOnly(True)
        self.use3.setObjectName("use3")
        self.seenLabel_6 = QtWidgets.QLabel(Dialog)
        self.seenLabel_6.setGeometry(QtCore.QRect(420, 240, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_6.setFont(font)
        self.seenLabel_6.setObjectName("seenLabel_6")
        self.seenLabel_7 = QtWidgets.QLabel(Dialog)
        self.seenLabel_7.setGeometry(QtCore.QRect(420, 480, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_7.setFont(font)
        self.seenLabel_7.setObjectName("seenLabel_7")
        self.seenLabel_8 = QtWidgets.QLabel(Dialog)
        self.seenLabel_8.setGeometry(QtCore.QRect(420, 730, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_8.setFont(font)
        self.seenLabel_8.setObjectName("seenLabel_8")
        self.seenLabel_9 = QtWidgets.QLabel(Dialog)
        self.seenLabel_9.setGeometry(QtCore.QRect(660, 240, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_9.setFont(font)
        self.seenLabel_9.setObjectName("seenLabel_9")
        self.seenLabel_10 = QtWidgets.QLabel(Dialog)
        self.seenLabel_10.setGeometry(QtCore.QRect(660, 480, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_10.setFont(font)
        self.seenLabel_10.setObjectName("seenLabel_10")
        self.seenLabel_11 = QtWidgets.QLabel(Dialog)
        self.seenLabel_11.setGeometry(QtCore.QRect(660, 730, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_11.setFont(font)
        self.seenLabel_11.setObjectName("seenLabel_11")
        self.seenLabel_12 = QtWidgets.QLabel(Dialog)
        self.seenLabel_12.setGeometry(QtCore.QRect(900, 240, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_12.setFont(font)
        self.seenLabel_12.setObjectName("seenLabel_12")
        self.seenLabel_13 = QtWidgets.QLabel(Dialog)
        self.seenLabel_13.setGeometry(QtCore.QRect(900, 480, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_13.setFont(font)
        self.seenLabel_13.setObjectName("seenLabel_13")
        self.seenLabel_14 = QtWidgets.QLabel(Dialog)
        self.seenLabel_14.setGeometry(QtCore.QRect(900, 730, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.seenLabel_14.setFont(font)
        self.seenLabel_14.setObjectName("seenLabel_14")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(70, 600, 121, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.seenLabel_15 = QtWidgets.QLabel(Dialog)
        self.seenLabel_15.setGeometry(QtCore.QRect(20, 570, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.seenLabel_15.setFont(font)
        self.seenLabel_15.setObjectName("seenLabel_15")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.movieLabel.setText(_translate("Dialog", "Selected Movie"))
        self.nextBttn.setText(_translate("Dialog", "Next Set"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.label_selected.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.seenLabel_2.setText(_translate("Dialog", "Official movie overview"))
        self.seenLabel_3.setText(_translate("Dialog", "Perspective 1"))
        self.seenLabel_4.setText(_translate("Dialog", "Perspective 2"))
        self.seenLabel_5.setText(_translate("Dialog", "Perspective 3"))
        self.seenLabel_6.setText(_translate("Dialog", "1"))
        self.seenLabel_7.setText(_translate("Dialog", "2"))
        self.seenLabel_8.setText(_translate("Dialog", "3"))
        self.seenLabel_9.setText(_translate("Dialog", "4"))
        self.seenLabel_10.setText(_translate("Dialog", "5"))
        self.seenLabel_11.setText(_translate("Dialog", "6"))
        self.seenLabel_12.setText(_translate("Dialog", "7"))
        self.seenLabel_13.setText(_translate("Dialog", "8"))
        self.seenLabel_14.setText(_translate("Dialog", "9"))
        self.comboBox.setItemText(0, _translate("Dialog", "1"))
        self.comboBox.setItemText(1, _translate("Dialog", "2"))
        self.comboBox.setItemText(2, _translate("Dialog", "3"))
        self.comboBox.setItemText(3, _translate("Dialog", "4"))
        self.comboBox.setItemText(4, _translate("Dialog", "5"))
        self.comboBox.setItemText(5, _translate("Dialog", "6"))
        self.comboBox.setItemText(6, _translate("Dialog", "7"))
        self.comboBox.setItemText(7, _translate("Dialog", "8"))
        self.comboBox.setItemText(8, _translate("Dialog", "9"))
        self.seenLabel_15.setText(_translate("Dialog", "Select next movie below"))

