# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testWindow2.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1770, 936)
        self.seenMovie = QtWidgets.QComboBox(Dialog)
        self.seenMovie.setGeometry(QtCore.QRect(30, 360, 69, 22))
        self.seenMovie.setObjectName("seenMovie")
        self.seenMovie.addItem("")
        self.seenMovie.addItem("")
        self.movieLabel = QtWidgets.QLabel(Dialog)
        self.movieLabel.setGeometry(QtCore.QRect(20, 40, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.movieLabel.setFont(font)
        self.movieLabel.setObjectName("movieLabel")
        self.nextBttn = QtWidgets.QPushButton(Dialog)
        self.nextBttn.setGeometry(QtCore.QRect(10, 640, 121, 51))
        self.nextBttn.setObjectName("nextBttn")
        self.seenLabel = QtWidgets.QLabel(Dialog)
        self.seenLabel.setGeometry(QtCore.QRect(30, 340, 161, 16))
        self.seenLabel.setObjectName("seenLabel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 230, 171, 211))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(750, 230, 171, 211))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(1270, 230, 171, 211))
        self.label_7.setObjectName("label_7")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(750, 470, 171, 211))
        self.label_5.setObjectName("label_5")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(1270, 470, 171, 211))
        self.label_8.setObjectName("label_8")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 470, 171, 211))
        self.label_2.setObjectName("label_2")
        self.label_selected = QtWidgets.QLabel(Dialog)
        self.label_selected.setGeometry(QtCore.QRect(20, 100, 171, 211))
        self.label_selected.setObjectName("label_selected")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(750, 720, 171, 211))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(230, 720, 171, 211))
        self.label_3.setObjectName("label_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(1270, 720, 171, 211))
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(940, 20, 271, 131))
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_3.setGeometry(QtCore.QRect(1460, 20, 241, 131))
        self.textEdit_3.setReadOnly(True)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_1.setGeometry(QtCore.QRect(420, 20, 241, 131))
        self.textEdit_1.setReadOnly(True)
        self.textEdit_1.setObjectName("textEdit_1")
        self.overview = QtWidgets.QTextEdit(Dialog)
        self.overview.setGeometry(QtCore.QRect(10, 420, 181, 201))
        self.overview.setReadOnly(True)
        self.overview.setObjectName("overview")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(230, 200, 171, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(750, 200, 171, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(Dialog)
        self.comboBox_3.setGeometry(QtCore.QRect(1280, 200, 171, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.textEdit_A = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A.setGeometry(QtCore.QRect(420, 270, 241, 141))
        self.textEdit_A.setReadOnly(True)
        self.textEdit_A.setObjectName("textEdit_A")
        self.textEdit_A2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A2.setGeometry(QtCore.QRect(420, 490, 241, 141))
        self.textEdit_A2.setReadOnly(True)
        self.textEdit_A2.setObjectName("textEdit_A2")
        self.textEdit_A3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A3.setGeometry(QtCore.QRect(420, 720, 241, 141))
        self.textEdit_A3.setReadOnly(True)
        self.textEdit_A3.setObjectName("textEdit_A3")
        self.textEdit_A6 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A6.setGeometry(QtCore.QRect(940, 720, 241, 141))
        self.textEdit_A6.setReadOnly(True)
        self.textEdit_A6.setObjectName("textEdit_A6")
        self.textEdit_A5 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A5.setGeometry(QtCore.QRect(940, 490, 241, 141))
        self.textEdit_A5.setReadOnly(True)
        self.textEdit_A5.setObjectName("textEdit_A5")
        self.textEdit_A4 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A4.setGeometry(QtCore.QRect(940, 270, 241, 141))
        self.textEdit_A4.setReadOnly(True)
        self.textEdit_A4.setObjectName("textEdit_A4")
        self.textEdit_A7 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A7.setGeometry(QtCore.QRect(1460, 270, 241, 141))
        self.textEdit_A7.setReadOnly(True)
        self.textEdit_A7.setObjectName("textEdit_A7")
        self.textEdit_A9 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A9.setGeometry(QtCore.QRect(1460, 720, 241, 141))
        self.textEdit_A9.setReadOnly(True)
        self.textEdit_A9.setObjectName("textEdit_A9")
        self.textEdit_A8 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_A8.setGeometry(QtCore.QRect(1460, 490, 241, 141))
        self.textEdit_A8.setReadOnly(True)
        self.textEdit_A8.setObjectName("textEdit_A8")
        self.seenLabel_2 = QtWidgets.QLabel(Dialog)
        self.seenLabel_2.setGeometry(QtCore.QRect(20, 400, 151, 16))
        self.seenLabel_2.setObjectName("seenLabel_2")
        self.seenLabel_3 = QtWidgets.QLabel(Dialog)
        self.seenLabel_3.setGeometry(QtCore.QRect(230, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_3.setFont(font)
        self.seenLabel_3.setObjectName("seenLabel_3")
        self.seenLabel_4 = QtWidgets.QLabel(Dialog)
        self.seenLabel_4.setGeometry(QtCore.QRect(750, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_4.setFont(font)
        self.seenLabel_4.setObjectName("seenLabel_4")
        self.seenLabel_5 = QtWidgets.QLabel(Dialog)
        self.seenLabel_5.setGeometry(QtCore.QRect(1270, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.seenLabel_5.setFont(font)
        self.seenLabel_5.setObjectName("seenLabel_5")
        self.textEdit_P1 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_P1.setGeometry(QtCore.QRect(500, 220, 161, 41))
        self.textEdit_P1.setObjectName("textEdit_P1")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(500, 160, 211, 41))
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setObjectName("label_10")
        self.checkBox_1 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_1.setGeometry(QtCore.QRect(420, 430, 291, 41))
        self.checkBox_1.setObjectName("checkBox_1")
        self.seenLabel_6 = QtWidgets.QLabel(Dialog)
        self.seenLabel_6.setGeometry(QtCore.QRect(240, 60, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.seenLabel_6.setFont(font)
        self.seenLabel_6.setObjectName("seenLabel_6")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(430, 650, 281, 41))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(430, 880, 281, 41))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_4.setGeometry(QtCore.QRect(950, 430, 281, 41))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_5 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_5.setGeometry(QtCore.QRect(950, 650, 281, 41))
        self.checkBox_5.setObjectName("checkBox_5")
        self.checkBox_6 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_6.setGeometry(QtCore.QRect(950, 880, 281, 41))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_7 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_7.setGeometry(QtCore.QRect(1470, 430, 291, 41))
        self.checkBox_7.setObjectName("checkBox_7")
        self.checkBox_8 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_8.setGeometry(QtCore.QRect(1470, 650, 291, 41))
        self.checkBox_8.setObjectName("checkBox_8")
        self.checkBox_9 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_9.setGeometry(QtCore.QRect(1470, 880, 291, 41))
        self.checkBox_9.setObjectName("checkBox_9")
        self.seenLabel_7 = QtWidgets.QLabel(Dialog)
        self.seenLabel_7.setGeometry(QtCore.QRect(770, 60, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.seenLabel_7.setFont(font)
        self.seenLabel_7.setObjectName("seenLabel_7")
        self.seenLabel_8 = QtWidgets.QLabel(Dialog)
        self.seenLabel_8.setGeometry(QtCore.QRect(1290, 60, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.seenLabel_8.setFont(font)
        self.seenLabel_8.setObjectName("seenLabel_8")
        self.textEdit_P2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_P2.setGeometry(QtCore.QRect(1020, 220, 161, 41))
        self.textEdit_P2.setObjectName("textEdit_P2")
        self.textEdit_P3 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_P3.setGeometry(QtCore.QRect(1550, 220, 151, 41))
        self.textEdit_P3.setObjectName("textEdit_P3")
        self.label_13 = QtWidgets.QLabel(Dialog)
        self.label_13.setGeometry(QtCore.QRect(230, 140, 251, 41))
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setObjectName("label_13")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(1020, 160, 211, 41))
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Dialog)
        self.label_12.setGeometry(QtCore.QRect(1550, 160, 211, 41))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(200, 10, 20, 931))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(710, 10, 20, 931))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(1230, 10, 20, 931))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(470, 160, 20, 91))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(990, 160, 20, 91))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(1520, 160, 20, 91))
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.label_14 = QtWidgets.QLabel(Dialog)
        self.label_14.setGeometry(QtCore.QRect(750, 140, 251, 41))
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Dialog)
        self.label_15.setGeometry(QtCore.QRect(1280, 150, 251, 41))
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setObjectName("label_15")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.seenMovie.setItemText(0, _translate("Dialog", "Yes"))
        self.seenMovie.setItemText(1, _translate("Dialog", "No"))
        self.movieLabel.setText(_translate("Dialog", "Selected Movie"))
        self.nextBttn.setText(_translate("Dialog", "Next Set"))
        self.seenLabel.setText(_translate("Dialog", "Have you seen the movie?"))
        self.label.setText(_translate("Dialog", "TextLabel"))
        self.label_4.setText(_translate("Dialog", "TextLabel"))
        self.label_7.setText(_translate("Dialog", "TextLabel"))
        self.label_5.setText(_translate("Dialog", "TextLabel"))
        self.label_8.setText(_translate("Dialog", "TextLabel"))
        self.label_2.setText(_translate("Dialog", "TextLabel"))
        self.label_selected.setText(_translate("Dialog", "TextLabel"))
        self.label_6.setText(_translate("Dialog", "TextLabel"))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.label_9.setText(_translate("Dialog", "TextLabel"))
        self.comboBox.setItemText(0, _translate("Dialog", "Totally Agree"))
        self.comboBox.setItemText(1, _translate("Dialog", "Somewhat Agree"))
        self.comboBox.setItemText(2, _translate("Dialog", "Don\'t Agree"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Totally Agree"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Somewhat Agree"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Don\'t Agree"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Totally Agree"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Somewhat Agree"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Don\'t Agree"))
        self.seenLabel_2.setText(_translate("Dialog", "Official movie overview"))
        self.seenLabel_3.setText(_translate("Dialog", "Perspective 1"))
        self.seenLabel_4.setText(_translate("Dialog", "Perspective 2"))
        self.seenLabel_5.setText(_translate("Dialog", "Perspective 3"))
        self.textEdit_P1.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label_10.setText(_translate("Dialog", "If you could name this perspective\n"
"by the elements the reviews have in\n"
"common, how would you call it?"))
        self.checkBox_1.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.seenLabel_6.setText(_translate("Dialog", "Review of Perspective 1\n"
"for the selected movie"))
        self.checkBox_2.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_3.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_4.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_5.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_6.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_7.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_8.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.checkBox_9.setText(_translate("Dialog", "This review seems related enough\n"
"to the review of the selected movie\n"
"for this perspective"))
        self.seenLabel_7.setText(_translate("Dialog", "Review of Perspective 2\n"
"for the selected movie"))
        self.seenLabel_8.setText(_translate("Dialog", "Review of Perspective 3\n"
"for the selected movie"))
        self.label_13.setText(_translate("Dialog", "Do you agree that these 3 movies\n"
"are related to the selected movie,\n"
"given the review above?"))
        self.label_11.setText(_translate("Dialog", "If you could name this perspective\n"
"by the elements the reviews have in\n"
"common, how would you call it?"))
        self.label_12.setText(_translate("Dialog", "If you could name this perspective\n"
"by the elements the reviews have in\n"
"common, how would you call it?"))
        self.label_14.setText(_translate("Dialog", "Do you agree that these 3 movies\n"
"are related to the selected movie,\n"
"given the review above?"))
        self.label_15.setText(_translate("Dialog", "Do you agree that these 3 movies\n"
"are related to the selected movie,\n"
"given the review above?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

